# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16keOG2c_3IC-XAoQhB4h0zFhqJb38uvF
"""

resposta=input('deseja ir a proxima tela')
if resposta =='sim':
  print('você foi para outra tela')
else:
    print('você saiu do sistema')

nome=input('informe o nome de usuario:')
sexo=input("informe 'F' para feminino e 'M' para masculino:").upper()
if(sexo=='M'):
    sexo = 'o'
elif(sexo== 'F'):
    sexo= 'a'
usuario=int(input('informe o tipo de usuário \n 1 - para adiministrador\n2 - para usuáruio comum \n3 - para membro associado'))
if(usuario==1):
    usuario ='adiministrador do sistema'
elif(usuario ==3):
    usuario= 'membro associado' 
elif(usuario ==2):
    usuario = 'usuario comum'
else:
    usuario='não existente'    
    
print(f' seja bem vind{sexo} {nome},a sua licença é de {usuario}')